.TH "AppInfo" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBgeneric_name\fP"
.br
.ti -1c
.RI "QString \fBcomment\fP"
.br
.ti -1c
.RI "QString \fBicon_name\fP"
.br
.ti -1c
.RI "QString \fBexec\fP"
.br
.ti -1c
.RI "QStringList \fBcategories\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
