.TH "panel::frontend::WLANIndicator" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::frontend::WLANIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBWlanStatusChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWLANIndicator\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBGetWlanIcon\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBwlan_icon\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
