.TH "panel::frontend::AppLauncher" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::frontend::AppLauncher
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppLauncher\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBlaunch\fP (const QString &exec)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
