.TH "panel::backend::TrayHandler" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::TrayHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBNewTrayIcon\fP (const QString &services)"
.br
.ti -1c
.RI "void \fBTrayIconDeleted\fP (const QString &services)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitDataServer\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
