.TH "panel::utils::LayerShellHelper" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::utils::LayerShellHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayerShellHelper\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "void \fBSetBarOnlyMask\fP (QObject *window_obj, int bar_height)"
.br
.ti -1c
.RI "void \fBSetBarAndDrawerMask\fP (QObject *window_obj, int bar_height, int drawer_x, int drawer_w, int drawer_h)"
.br
.ti -1c
.RI "void \fBSetFullMask\fP (QObject *window_obj)"
.br
.ti -1c
.RI "void \fBSetupOverlayWindow\fP (QObject *window_obj)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetBarOnlyMask\fP (QObject *window_obj, int bar_height)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetBarAndDrawerMask\fP (QObject *window_obj, int bar_height, int drawer_x, int drawer_w, int drawer_h)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetFullMask\fP (QObject *window_obj)"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsetupOverlayWindow\fP (QObject *window_obj)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
