.TH "panel::backend::UserInfo" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::UserInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserInfo\fP (QObject *parent=nullptr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBGetUserName\fP ()"
.br
.ti -1c
.RI "static QString \fBGetUserAvatarPath\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBuserName\fP"
.br
.ti -1c
.RI "QString \fBavatarPath\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
