.TH "panel::backend::SessionHandler" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::SessionHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSessionHandler\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBLogout\fP ()"
.br
.ti -1c
.RI "void \fBSwitchUser\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBlock\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBlogout\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBswitchUser\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
