.TH "panel::loader::SchemeTuple" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::loader::SchemeTuple
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< material_color_utilities::DynamicScheme > \fBlight\fP"
.br
.ti -1c
.RI "std::unique_ptr< material_color_utilities::DynamicScheme > \fBdark\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
