.TH "panel::backend::PowerOptions" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::PowerOptions
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPowerOptions\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "void \fBSuspend\fP ()"
.br
.ti -1c
.RI "void \fBHibernate\fP ()"
.br
.ti -1c
.RI "void \fBReboot\fP ()"
.br
.ti -1c
.RI "void \fBPowerOff\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBsuspend\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBhibernate\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBreboot\fP ()"
.br
.ti -1c
.RI "Q_INVOKABLE void \fBpowerOff\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
