.TH "panel::utils::Log" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::utils::Log
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBInfo\fP (const QString &tag, const QString &content)"
.br
.ti -1c
.RI "static QString \fBInfo\fP (const QString &tag, const QString &title, const QString &content)"
.br
.ti -1c
.RI "static QString \fBOk\fP (const QString &tag, const QString &content)"
.br
.ti -1c
.RI "static QString \fBOk\fP (const QString &tag, const QString &title, const QString &content)"
.br
.ti -1c
.RI "static QString \fBWarn\fP (const QString &tag, const QString &content)"
.br
.ti -1c
.RI "static QString \fBWarn\fP (const QString &tag, const QString &title, const QString &content)"
.br
.ti -1c
.RI "static QString \fBError\fP (const QString &tag, const QString &content)"
.br
.ti -1c
.RI "static QString \fBError\fP (const QString &tag, const QString &title, const QString &content)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
