.TH "panel::loader::FontLoader" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::loader::FontLoader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QFont \fBGetOutlinedMaterialSymbolFont\fP ()"
.br
.ti -1c
.RI "static QFont \fBGetRoundedMaterialSymbolFont\fP ()"
.br
.ti -1c
.RI "static QFont \fBGetSharpMaterialSymbolFont\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
