.TH "panel::frontend::BatteryIndicator" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::frontend::BatteryIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBBatteryStatusChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatteryIndicator\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBGetBatteryIcon\fP () const"
.br
.ti -1c
.RI "bool \fBGetIsCharging\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBbattery_icon\fP"
.br
.ti -1c
.RI "bool \fBis_charging\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
