.TH "panel::loader::TranslationLoader" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::loader::TranslationLoader
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTranslationLoader\fP (const QString &file, const LanguageType &fallback_lng)"
.br
.ti -1c
.RI "QString \fBGetLocaleSuffix\fP (const LanguageType &type)"
.br
.ti -1c
.RI "QString \fBGetLocaleDisplayName\fP (const LanguageType &type)"
.br
.ti -1c
.RI "QString \fBGetTranslation\fP (const QString &message)"
.br
.ti -1c
.RI "Q_INVOKABLE QString \fBTr\fP (const QString &message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
