.TH "panel::loader::QuickThemeProvider" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::loader::QuickThemeProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBSchemeUpdated\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuickThemeProvider\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "void \fBRefreshTheme\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStatusBarBg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStatusBarPrimary\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStatusBarSurfaceFg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStatusBarStateLayerHover\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStatusBarStateLayerPressed\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetPrimary\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceContainer\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceFg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStateLayerHover\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetStateLayerPressed\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceBg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceContainerLow\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceContainerLowest\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceContainerHigh\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSurfaceVariantFg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetPrimaryContainer\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSecondaryContainer\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSecondaryContainerFg\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetError\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetErrorContainer\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetOnErrorContainer\fP ()"
.br
.ti -1c
.RI "const QColor \fBGetSecondary\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QColor \fBstatus_bar_bg\fP"
.br
.ti -1c
.RI "QColor \fBstatus_bar_primary\fP"
.br
.ti -1c
.RI "QColor \fBstatus_bar_surface_fg\fP"
.br
.ti -1c
.RI "QColor \fBstatus_bar_state_layer_hover\fP"
.br
.ti -1c
.RI "QColor \fBstatus_bar_state_layer_pressed\fP"
.br
.ti -1c
.RI "QColor \fBprimary\fP"
.br
.ti -1c
.RI "QColor \fBsurface_container\fP"
.br
.ti -1c
.RI "QColor \fBsurface_fg\fP"
.br
.ti -1c
.RI "QColor \fBstate_layer_hover\fP"
.br
.ti -1c
.RI "QColor \fBstate_layer_pressed\fP"
.br
.ti -1c
.RI "QColor \fBsurface_bg\fP"
.br
.ti -1c
.RI "QColor \fBsurface_container_low\fP"
.br
.ti -1c
.RI "QColor \fBsurface_variant_fg\fP"
.br
.ti -1c
.RI "QColor \fBprimary_container\fP"
.br
.ti -1c
.RI "QColor \fBsecondary_container\fP"
.br
.ti -1c
.RI "QColor \fBsecondary_container_fg\fP"
.br
.ti -1c
.RI "QColor \fBsurface_container_lowest\fP"
.br
.ti -1c
.RI "QColor \fBsurface_container_high\fP"
.br
.ti -1c
.RI "QColor \fBerror\fP"
.br
.ti -1c
.RI "QColor \fBerror_container\fP"
.br
.ti -1c
.RI "QColor \fBon_error_container\fP"
.br
.ti -1c
.RI "QColor \fBsecondary\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
