.TH "panel::backend::SNIToolTip" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::SNIToolTip
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBiconName\fP"
.br
.ti -1c
.RI "QList< \fBSNIImage\fP > \fBiconData\fP"
.br
.ti -1c
.RI "QString \fBtitle\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
