.TH "panel::frontend::TrayIconImageHandler" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::frontend::TrayIconImageHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits QQuickImageProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrayIconImageHandler\fP (\fBSystemTrayHandler\fP *handler)"
.br
.ti -1c
.RI "QImage \fBrequestImage\fP (const QString &id, QSize *size, const QSize &requested_size) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
