.TH "panel::frontend::AppIndicator" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::frontend::AppIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBDataChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppIndicator\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBGetAppName\fP () const"
.br
.ti -1c
.RI "QString \fBGetPackageName\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBapp_name\fP"
.br
.ti -1c
.RI "QString \fBpackage_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
