.TH "panel::backend::CurrentWindowInfo" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::CurrentWindowInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBapplication_name\fP"
.br
.ti -1c
.RI "QString \fBpackage_name\fP"
.br
.ti -1c
.RI "uint \fBpid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
