.TH "panel::loader::StyleTuple" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::loader::StyleTuple
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBlight_style\fP"
.br
.ti -1c
.RI "QString \fBdark_style\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
