.TH "panel::backend::CurrentWindowKwinImpl" 3 "Version 0.9.5 - Unstable" "Husky Panel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel::backend::CurrentWindowKwinImpl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpanel::backend::CurrentWindowProvider\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "Q_INVOKABLE void \fBUpdateActiveApp\fP (QString name, QString appid, QString title)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCurrentWindowKwinImpl\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBGetApplicationName\fP () override"
.br
.ti -1c
.RI "QString \fBGetPackageName\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBpanel::backend::CurrentWindowProvider\fP
.in +1c
.ti -1c
.RI "\fBCurrentWindowProvider\fP (QObject *parent=nullptr)"
.br
.in -1c
.SS "Additional Inherited Members"


Signals inherited from \fBpanel::backend::CurrentWindowProvider\fP
.in +1c
.ti -1c
.RI "void \fBCurrentWindowChanged\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "QString panel::backend::CurrentWindowKwinImpl::GetApplicationName ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBpanel::backend::CurrentWindowProvider\fP\&.
.SS "QString panel::backend::CurrentWindowKwinImpl::GetPackageName ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBpanel::backend::CurrentWindowProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Husky Panel from the source code\&.
